services:
  db:
    image: postgres:13
    container_name: hotels-app-db
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
      POSTGRES_DB: hotels
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: node:18
    container_name: hotels-app
    working_dir: /usr/src/app
    environment:
      DATABASE: hotels
      DATABASE_USER: development
      DATABASE_PASSWORD: development
      DATABASE_URL: "db"
      DATABASE_PORT: 5432
      PORT: 3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
